# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.0
group=me.andreasmelone
java_version=21

# Common
minecraft_version=1.21.4
mod_name=PinkFont
mod_author=AndreasMelone
mod_id=pinkfont
license=MIT
credits=
description=Allows you to change the color of text in Minecraft!
minecraft_version_range=[1.21.4, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_version=0.118.0+1.21.4
fabric_loader_version=0.16.9

# NeoForge
neoforge_version=21.4.154
neoforge_loader_version_range=[4,)

# Yacl
yacl_version=3.7.1+1.21.4

# Mod menu
modmenu_version=13.0.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
